
project_id = "qyipyygojlfhdghnraus"

[functions.hostaway-sync]
verify_jwt = false

[functions.insert-properties]
verify_jwt = false

[functions.setup-automation]
verify_jwt = false

[functions.send-task-assignment-email]
verify_jwt = false

[functions]
  [functions.hostaway-sync]
    import_map = "import_map.json"
  [functions.insert-properties]
    import_map = "import_map.json"
  [functions.setup-automation]
    import_map = "import_map.json"
  [functions.send-task-assignment-email]
    import_map = "import_map.json"
